# Generated by Django 4.0.4 on 2022-06-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_order_product_order_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qnt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
