# Generated by Django 4.0.4 on 2022-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order_qnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='sponseredId',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='status',
            field=models.CharField(default='under-review', max_length=200),
        ),
    ]
