# Generated by Django 4.0.4 on 2022-06-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dealer_sponseredid_alter_dealer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='status',
            field=models.CharField(default='under-review', max_length=100),
        ),
    ]
