# Generated by Django 4.0.4 on 2022-06-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_distributor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='distributor',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
