# Generated by Django 4.0.4 on 2022-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_distributor_email_distributor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='paidAmount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='paidDate',
        ),
        migrations.AddField(
            model_name='transaction',
            name='requestAmount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requestDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='unpaid', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(default='Credit', max_length=300),
        ),
    ]
