# Generated by Django 4.0.4 on 2022-06-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_amount_transaction_paidamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dealer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inbox',
            name='status',
            field=models.CharField(default='new', max_length=200),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='status',
            field=models.CharField(default='new', max_length=100),
        ),
    ]
