# Generated by Django 4.0.1 on 2022-10-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_productreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
