# Generated by Django 4.0.1 on 2022-10-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_productreviews_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
