# Generated by Django 4.0.1 on 2022-10-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_order_address_order_city_order_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='msg',
            field=models.TextField(default='', null=True),
        ),
    ]
